# Generated by Django 4.2.3 on 2023-08-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_nuevoblog_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevoblog',
            name='tematica',
            field=models.CharField(choices=[('politica', 'Politica'), ('deportes', 'Deportes'), ('naturaleza', 'Naturaleza'), ('otro', 'Otro')], default='politica', max_length=15),
        ),
    ]
